<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.eclipse.org/bugs/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.7"
          urlbase="https://bugs.eclipse.org/bugs/"
          
          maintainer="webmaster@eclipse.org"
>

    <bug>
          <bug_id>359470</bug_id>
          
          <creation_ts>2011-09-29 15:16:00 -0400</creation_ts>
          <short_desc>[subclipse] Exception when creating a review item from a new  file</short_desc>
          <delta_ts>2011-09-29 23:43:59 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>14</classification_id>
          <classification>Mylyn</classification>
          <product>Mylyn Versions</product>
          <component>Framework</component>
          <version>0.8</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>P3</priority>
          <bug_severity>normal</bug_severity>
          <target_milestone>0.9</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Alvaro Sanchez-Leon">alvsan09</reporter>
          <assigned_to name="Alvaro Sanchez-Leon">alvsan09</assigned_to>
          <cc>lmcbout</cc>
    
    <cc>marco.masse</cc>
    
    <cc>sebastien.dubois</cc>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>2002696</commentid>
    <comment_count>0</comment_count>
    <who name="Alvaro Sanchez-Leon">alvsan09</who>
    <bug_when>2011-09-29 15:16:15 -0400</bug_when>
    <thetext>An exception is triggered when crating review items from new files.

this does not happen when using Git as a vcs, but happes with all other supported connectors</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2002702</commentid>
    <comment_count>1</comment_count>
    <who name="Alvaro Sanchez-Leon">alvsan09</who>
    <bug_when>2011-09-29 15:21:33 -0400</bug_when>
    <thetext>java.lang.NullPointerException
	at org.eclipse.mylyn.internal.subclipse.core.SubclipseConnector.getArtifact(SubclipseConnector.java:96)
	at org.eclipse.mylyn.versions.core.spi.ScmConnector.getArtifact(ScmConnector.java:36)
	at org.eclipse.mylyn.reviews.r4e.ui.internal.utils.CommandUtils.updateBaseFile(CommandUtils.java:253)
	at org.eclipse.mylyn.reviews.r4e.ui.internal.utils.CommandUtils.getBaseFileData(CommandUtils.java:211)
	at org.eclipse.mylyn.reviews.r4e.ui.internal.commands.NewReviewItemHandler.addReviewItemFromText(NewReviewItemHandler.java:184)
	at org.eclipse.mylyn.reviews.r4e.ui.internal.commands.NewReviewItemHandler.access$0(NewReviewItemHandler.java:179)
	at org.eclipse.mylyn.reviews.r4e.ui.internal.commands.NewReviewItemHandler$1.runInUIThread(NewReviewItemHandler.java:107)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4140)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1410)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2002872</commentid>
    <comment_count>2</comment_count>
    <who name="Alvaro Sanchez-Leon">alvsan09</who>
    <bug_when>2011-09-29 23:43:14 -0400</bug_when>
    <thetext>A validation of resolution of artifact was missing.
It&apos;s now fixed.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2002873</commentid>
    <comment_count>3</comment_count>
    <who name="Alvaro Sanchez-Leon">alvsan09</who>
    <bug_when>2011-09-29 23:43:59 -0400</bug_when>
    <thetext>see comment above</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>