<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugs.eclipse.org/bugs/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.7"
          urlbase="https://bugs.eclipse.org/bugs/"
          
          maintainer="webmaster@eclipse.org"
>

    <bug>
          <bug_id>420946</bug_id>
          
          <creation_ts>2013-11-02 14:58:00 -0400</creation_ts>
          <short_desc>Device is disposed error in TaskListBackupManager.backupNow</short_desc>
          <delta_ts>2013-11-08 08:03:06 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>14</classification_id>
          <classification>Mylyn</classification>
          <product>Mylyn Tasks</product>
          <component>Framework</component>
          <version>unspecified</version>
          <rep_platform>All</rep_platform>
          <op_sys>All</op_sys>
          <bug_status>RESOLVED</bug_status>
          <resolution>FIXED</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>P3</priority>
          <bug_severity>minor</bug_severity>
          <target_milestone>3.11</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Frank Becker">eclipse</reporter>
          <assigned_to name="Frank Becker">eclipse</assigned_to>
          <cc>sam.davis</cc>
    
    <cc>tomasz.zarna</cc>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>2325891</commentid>
    <comment_count>0</comment_count>
    <who name="Frank Becker">eclipse</who>
    <bug_when>2013-11-02 14:58:42 -0400</bug_when>
    <thetext>!ENTRY org.eclipse.core.jobs 4 2 2013-11-02 19:44:40.869
!MESSAGE An internal error occurred during: &quot;Task Data Snapshot&quot;.
!STACK 0
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.SWT.error(SWT.java:4334)
	at org.eclipse.swt.SWT.error(SWT.java:4305)
	at org.eclipse.swt.widgets.Display.error(Display.java:1077)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:588)
	at org.eclipse.mylyn.internal.tasks.ui.TaskListBackupManager.backupNow(TaskListBackupManager.java:154)
	at org.eclipse.mylyn.internal.tasks.ui.TaskListBackupManager$1.run(TaskListBackupManager.java:87)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2325892</commentid>
    <comment_count>1</comment_count>
    <who name="Frank Becker">eclipse</who>
    <bug_when>2013-11-02 15:08:27 -0400</bug_when>
    <thetext>A fix is in review https://git.eclipse.org/r/#/c/18009/</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>2328053</commentid>
    <comment_count>2</comment_count>
    <who name="Steffen Pingel">steffen.pingel</who>
    <bug_when>2013-11-08 08:03:06 -0500</bug_when>
    <thetext>Merged. Thanks! We&apos;ll likely get the underlying error logged now but we can track that on a separate bug.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>