BUG REPORT COMMENTS:
I20080530-1730

Eclipse rightly reports an error on the following source:
public class X {
  public static void main(String args[]) {
	final int i; // def. un.
	try {
	  if (false) {
		// def. un.
		i = 0;
		// def. as.
		throw new MyException() /* def. as. */;
		// def. un. & as.
	  }
	} catch (MyException e) {
	  /* not def. un. because not def. un. after e in every statement of the 
	   * form throw e that belongs to the try block */
	  i = 1; // error
	}
  }
}
class MyException extends Exception {
}

(comments follow the definition for definite assignment and definite unassignment of JLS 3 § 16).

While JLS 3 § 16.2.15 does not consider exception types at all in its rules for try statements, Eclipse compiles the following *without any error*:
public class X {
  public static void main(String args[]) {
	final int i; // def. un.
	try {
	  if (false) {
		// def. un.
		i = 0;
		// def. as.
		throw new MyException() /* def. as. */;
		// def. un. & as.
	  }
	} catch (Exception e) {
	  /* not def. un. because no

