BUG REPORT COMMENTS:
20030128
class Test{
	void foo(){
		throw new <<CODE ASSIST HERE
	}
}

inserts Test right away.
2 problems:

a.Test is not a subclass of Throwable, so it makes no sense
b.more than 1 proposal should be presented

--
side note:
it's incorrect after any 'new', I think - it always just puts in the name of 
the enclosing class
Current behavior :
- if there is at least a character then all types are proposed. Otherwise only 
enclosings types and top level types of the current unit are proposed (avoid to 
suggest all types of the workspace).
- in a 'throw' statement all possible types are proposed, but relevance of 
exceptions is higher. Currently a proposed type is considered as an exception 
if his name contains 'exception' or 'error' (compute hierarchy is too costly).

So, all seems to work as design ;)

Adam - Any comment ? If there is no comment, i close this bug.
ok to close then
closing.

